<a href="https://colab.research.google.com/github/andytilia/pandas-sandbox/blob/main/footystats.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
players = pd.read_csv("https://raw.githubusercontent.com/andytilia/pandas-sandbox/main/england-premier-league-players-2018-to-2019-stats.csv")
players.head()

         full_name  age  ...  rank_in_league_top_defenders rank_in_club_top_scorer
0  Aaron Cresswell   30  ...                            80                      20
1     Aaron Lennon   33  ...                            -1                      10
2       Aaron Mooy   30  ...                            -1                       3
3     Aaron Ramsey   29  ...                            -1                       5
4       Aaron Rowe   20  ...                            -1                      31

[5 rows x 46 columns]

In [9]:
players.columns

Index(['full_name', 'age', 'birthday', 'league', 'season', 'position',
       'Current Club', 'minutes_played_overall', 'minutes_played_home',
       'minutes_played_away', 'nationality', 'appearances_overall',
       'appearances_home', 'appearances_away', 'goals_overall', 'goals_home',
       'goals_away', 'assists_overall', 'assists_home', 'assists_away',
       'penalty_goals', 'penalty_misses', 'clean_sheets_overall',
       'clean_sheets_home', 'clean_sheets_away', 'conceded_overall',
       'conceded_home', 'conceded_away', 'yellow_cards_overall',
       'red_cards_overall', 'goals_involved_per_90_overall',
       'assists_per_90_overall', 'goals_per_90_overall', 'goals_per_90_home',
       'goals_per_90_away', 'min_per_goal_overall', 'conceded_per_90_overall',
       'min_per_conceded_overall', 'min_per_match', 'min_per_card_overall',
       'min_per_assist_overall', 'cards_per_90_overall',
       'rank_in_league_top_attackers', 'rank_in_league_top_midfielders',
       'rank_in_league_top_defenders', 'rank_in_club_top_scorer'],
      dtype='object')

In [17]:
players["age"].describe()

count    572.000000
mean      27.617133
std        4.681287
min        0.000000
25%       24.000000
50%       28.000000
75%       31.000000
max       41.000000
Name: age, dtype: float64

In [28]:
players[players["age"] == 0]

         full_name  age  ...  rank_in_league_top_defenders rank_in_club_top_scorer
70     Bakayo Sako    0  ...                            -1                      17
219  Harvey Elliot    0  ...                            -1                      28

[2 rows x 46 columns]

In [27]:
players[players["Current Club"] == "Liverpool"]

                          full_name  ...  rank_in_club_top_scorer
10               Adam David Lallana  ...                       18
20                   Alberto Moreno  ...                       17
24          Alex Oxlade-Chamberlain  ...                       21
36                   Alisson Becker  ...                       16
45                 Andrew Robertson  ...                       20
126                    Curtis Jones  ...                       -1
133                Daniel Sturridge  ...                       10
155                    Dejan Lovren  ...                       12
163                    Divock Origi  ...                        7
184                         Fabinho  ...                       15
206             Georginio Wijnaldum  ...                        8
247                    James Milner  ...                        5
272                       Joe Gomez  ...                       19
277                      Joel Matip  ...                       11
291                Jordan Henderson  ...                       14
348                    Loris Karius  ...                       -1
411                   Mohamed Salah  ...                        2
417                 Naby Deco Keïta  ...                        9
458  Rafael Euclides Soares Camacho  ...                       -1
471                 Roberto Firmino  ...                        3
489                      Sadio Mané  ...                        1
512                  Simon Mignolet  ...                       -1
539          Trent Alexander-Arnold  ...                       13
553                 Virgil van Dijk  ...                        6
563                 Xherdan Shaqiri  ...                        4

[25 rows x 46 columns]

In [34]:
matches = pd.read_csv("https://raw.githubusercontent.com/andytilia/pandas-sandbox/main/england-premier-league-matches-2018-to-2019-stats.csv")
matches.head()

    timestamp  ...                                       stadium_name
0  1533927600  ...                          Old Trafford (Manchester)
1  1533987000  ...              St. James' Park (Newcastle upon Tyne)
2  1533996000  ...             Vitality Stadium (Bournemouth- Dorset)
3  1533996000  ...                            Craven Cottage (London)
4  1533996000  ...  John Smith's Stadium (Huddersfield- West Yorks...

[5 rows x 64 columns]

In [43]:
ref_matches = pd.DataFrame(matches.groupby("referee")["timestamp"].count())
ref_matches

                 timestamp
referee
Andre Marriner          27
Andy Madley              2
Anthony Taylor          32
Chris Kavanagh          24
Craig Pawson            26
David Coote             11
Graham Scott            17
Jonathan Moss           27
Kevin Friend            27
Lee Mason               19
Lee Probert             18
Martin Atkinson         29
Michael Oliver          30
Mike Dean               29
Paul Tierney            24
Roger East              10
Simon Hooper             8
Stuart Attwell          20

In [57]:
ref_hy = pd.DataFrame(matches.groupby("referee")["home_team_yellow_cards"].sum())
ref_ay = pd.DataFrame(matches.groupby("referee")["away_team_yellow_cards"].sum())
ref_hr = pd.DataFrame(matches.groupby("referee")["home_team_red_cards"].sum())
ref_ar = pd.DataFrame(matches.groupby("referee")["away_team_red_cards"].sum())
yellows = pd.merge(ref_hy, ref_ay, on='referee', how='inner')
reds = pd.merge(ref_hr, ref_ar, on='referee', how='inner')
ref_cards = pd.merge(yellows, reds, on="referee", how="inner")
ref_cards = pd.merge(ref_cards, ref_matches, on="referee", how="inner")
ref_cards.columns = ["hy", "ay", "hr", "ar", "m"]
ref_cards

                 hy  ay  hr  ar   m
referee
Andre Marriner   33  43   2   1  27
Andy Madley       0   2   0   0   2
Anthony Taylor   57  45   0   1  32
Chris Kavanagh   39  36   1   1  24
Craig Pawson     46  46   1   6  26
David Coote      16  19   0   0  11
Graham Scott     14  24   0   1  17
Jonathan Moss    47  50   3   2  27
Kevin Friend     48  44   2   1  27
Lee Mason        30  33   1   0  19
Lee Probert      20  28   1   3  18
Martin Atkinson  38  53   0   1  29
Michael Oliver   35  50   3   4  30
Mike Dean        64  70   3   7  29
Paul Tierney     37  45   1   0  24
Roger East       23  21   0   0  10
Simon Hooper      9  11   0   0   8
Stuart Attwell   31  32   0   1  20

In [63]:
ref_cards['yellows'] = ref_cards['ay']+ref_cards['hy']
ref_cards['ypg'] = ref_cards['yellows']/ref_cards['m']
ref_cards['reds'] = ref_cards['ar']+ref_cards['hr']
ref_cards['rpg'] = ref_cards['reds']/ref_cards['m']
ref_cards

                 hy  ay  hr  ar   m  yellows       ypg  reds       rpg
referee
Andre Marriner   33  43   2   1  27       76  2.814815     3  0.111111
Andy Madley       0   2   0   0   2        2  1.000000     0  0.000000
Anthony Taylor   57  45   0   1  32      102  3.187500     1  0.031250
Chris Kavanagh   39  36   1   1  24       75  3.125000     2  0.083333
Craig Pawson     46  46   1   6  26       92  3.538462     7  0.269231
David Coote      16  19   0   0  11       35  3.181818     0  0.000000
Graham Scott     14  24   0   1  17       38  2.235294     1  0.058824
Jonathan Moss    47  50   3   2  27       97  3.592593     5  0.185185
Kevin Friend     48  44   2   1  27       92  3.407407     3  0.111111
Lee Mason        30  33   1   0  19       63  3.315789     1  0.052632
Lee Probert      20  28   1   3  18       48  2.666667     4  0.222222
Martin Atkinson  38  53   0   1  29       91  3.137931     1  0.034483
Michael Oliver   35  50   3   4  30       85  2.833333     7  0.233333
Mike Dean        64  70   3   7  29      134  4.620690    10  0.344828
Paul Tierney     37  45   1   0  24       82  3.416667     1  0.041667
Roger East       23  21   0   0  10       44  4.400000     0  0.000000
Simon Hooper      9  11   0   0   8       20  2.500000     0  0.000000
Stuart Attwell   31  32   0   1  20       63  3.150000     1  0.050000

In [38]:
matches.columns

Index(['timestamp', 'date_GMT', 'status', 'attendance', 'home_team_name',
       'away_team_name', 'referee', 'Game Week', 'Pre-Match PPG (Home)',
       'Pre-Match PPG (Away)', 'home_ppg', 'away_ppg', 'home_team_goal_count',
       'away_team_goal_count', 'total_goal_count', 'total_goals_at_half_time',
       'home_team_goal_count_half_time', 'away_team_goal_count_half_time',
       'home_team_goal_timings', 'away_team_goal_timings',
       'home_team_corner_count', 'away_team_corner_count',
       'home_team_yellow_cards', 'home_team_red_cards',
       'away_team_yellow_cards', 'away_team_red_cards',
       'home_team_first_half_cards', 'home_team_second_half_cards',
       'away_team_first_half_cards', 'away_team_second_half_cards',
       'home_team_shots', 'away_team_shots', 'home_team_shots_on_target',
       'away_team_shots_on_target', 'home_team_shots_off_target',
       'away_team_shots_off_target', 'home_team_fouls', 'away_team_fouls',
       'home_team_possession', 'away_team_possession', 'team_a_xg',
       'team_b_xg', 'average_goals_per_match_pre_match',
       'btts_percentage_pre_match', 'over_15_percentage_pre_match',
       'over_25_percentage_pre_match', 'over_35_percentage_pre_match',
       'over_45_percentage_pre_match', 'over_15_HT_FHG_percentage_pre_match',
       'over_05_HT_FHG_percentage_pre_match',
       'over_15_2HG_percentage_pre_match', 'over_05_2HG_percentage_pre_match',
       'average_corners_per_match_pre_match',
       'average_cards_per_match_pre_match', 'odds_ft_home_team_win',
       'odds_ft_draw', 'odds_ft_away_team_win', 'odds_ft_over15',
       'odds_ft_over25', 'odds_ft_over35', 'odds_ft_over45', 'odds_btts_yes',
       'odds_btts_no', 'stadium_name'],
      dtype='object')